version: "3.9"
services:
 apidev-project-service:
  image: tukke/apidev-project
  ports:
    - "8000:8000"
  volumes:
    - sqlite_apidev-project_volume:/code/sqlitedb

volumes:
  sqlite_apidev-project_volume:
